theme = "nord-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

#[[block]]
#block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
dynamic_width = true
hide_when_empty = true
max_width = 30

[[block]]
block = "custom"
command = "whoami"
interval = "once"

[[block]]
block = "custom"
command = "cat /etc/hostname"
interval = "once"

[[block]]
block = "custom"
command = "echo `uname` `uname -r | tr - . | cut -d. -f1-2`"
interval = "once"

#[[block]]
#block = "battery"
#if_command = "test -e /sys/class/power_supply/BAT0"
